services:

  #  db:
  #    image: postgres
  #    restart: always
  #    environment:
  #      - POSTGRES_USER=admin
  #      - POSTGRES_PASSWORD=password
  #    ports:
  #      - '5432:5432'
  #
  #  adminer:
  #    image: adminer
  #    restart: always
  #    ports:
  #      - "8080:8080"

#  devcontainer:
#    build:
#      context: .
#      dockerfile: Dockerfile
